### ISSUE TITLE
Maritime Smart Data Models

### ISSUE THREAD

**Issue by kapsali29** [smart-data-models/CrossSector#2]
Dear all,

In the context of VesselAI H2020 we are building a common data model for Maritime Industry. More specifically we have re-used existing FIWARE data models and their concepts to construct Vessel's Operation schema, Vessel Engine Operation, port that a Vessel begins VesselConsumption and Vessel Emitted data.
We would like to contribute our common data model, as it will be open source. What is the procedure?
Thanks in advance

**Comment by albertoabellagarcia** [comment]
1) Here you have the [contribution manual](https://bit.ly/contribution_manual) 
2) We have invited you to the incubated repository and we have granted permission for it to your user. Please work in this folder [https://github.com/smart-data-models/incubated/tree/master/SMARTLOGISTICS/Vessel](https://github.com/smart-data-models/incubated/tree/master/SMARTLOGISTICS/Vessel) 
3) The empty files on it are the minimum mandatory files. Mind the contribution manual as long as most of the files you see in a published data model are created automatically 
4) If you need some support you only have to go to some of the open sessions Mondays at 14:00 at this link [https://bit.ly/smartdatamodels](https://bit.ly/smartdatamodels) (next is 18th)
5) or you can just drop us an email to [info@smartdatamodels.org](info@smartdatamodels.org)
6) If you want others to collaborate with you click this [link](https://smartdatamodels.org/index.php/new-incubated-data-models/) and fill the form you will be then [listed](https://smartdatamodels.org/index.php/projects/).
7) A couple of services to create your json schema (the single source of truth of your data model)
7.1) [create a documented json schema](https://smartdatamodels.org/index.php/generate-you-schema-out-of-your-payload/) from a key values payload (Available  in the right menu block at smartdatamodels.org
7.2) An [online editor](https://smartdatamodels.org/index.php/draft-a-data-model/) for json schema with template and the [9 minutes video](https://smartdatamodels.org/index.php/learning-zone/) for using it (also at smartdtamodels.org)
